
name: First workflow # this is the name of the workflow

on: [push] # trigger the workflow on push events

jobs:
  build: # this is the job name
    runs-on: ubuntu-latest # specify the runner environment

    steps: 
    - name: first step
      run: |
       echo "Hello, world!"
       echo "This is my first GitHub Actions workflow."
    
