
name: multiple workflow # this is the name of the workflow

on: 
  push: # trigger the workflow on push events
    branches:
      - main

jobs:
  first workflow job:
    runs-on: ubuntu-latest # specify the runner environment

    steps: 
    - name: first step
      run: |
       echo "Hello, world!"
       echo "This is job 1."
  second workflow job:
    runs-on: ubuntu-latest # specify the runner environment
    steps: 
    - name: first step
      run: |
       echo "Hello, world!"
       echo "This is job 1."
    
